name: RSS Feed Action

on:
  schedule:
    - cron: '0 0 * * *'  # Corrected cron schedule for daily at midnight UTC
  workflow_dispatch:

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Run RSS Feed Action
        uses: ./ 
        with:
          feeds_file: 'feeds.yml'
